// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUV5lrfbZj6VRyW9hBkWW1IjiRw1ldf0M',
    appId: '1:427705120004:web:30339dce9ab24767608c51',
    messagingSenderId: '427705120004',
    projectId: 'softwarelab-d0a18',
    authDomain: 'softwarelab-d0a18.firebaseapp.com',
    storageBucket: 'softwarelab-d0a18.appspot.com',
    measurementId: 'G-XN498Z43DN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0X_FZbmKd9yDQhWfMz-cGrrEs_fMFmK8',
    appId: '1:427705120004:android:b2419fb3bfbb6d50608c51',
    messagingSenderId: '427705120004',
    projectId: 'softwarelab-d0a18',
    storageBucket: 'softwarelab-d0a18.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeyiInAgt7stiltUTWZYaSXx9avrJEDxA',
    appId: '1:427705120004:ios:6e704d4c3a8d9861608c51',
    messagingSenderId: '427705120004',
    projectId: 'softwarelab-d0a18',
    storageBucket: 'softwarelab-d0a18.appspot.com',
    iosBundleId: 'com.example.softwarelab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeyiInAgt7stiltUTWZYaSXx9avrJEDxA',
    appId: '1:427705120004:ios:6e704d4c3a8d9861608c51',
    messagingSenderId: '427705120004',
    projectId: 'softwarelab-d0a18',
    storageBucket: 'softwarelab-d0a18.appspot.com',
    iosBundleId: 'com.example.softwarelab',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUV5lrfbZj6VRyW9hBkWW1IjiRw1ldf0M',
    appId: '1:427705120004:web:db8c952e8b1d6e08608c51',
    messagingSenderId: '427705120004',
    projectId: 'softwarelab-d0a18',
    authDomain: 'softwarelab-d0a18.firebaseapp.com',
    storageBucket: 'softwarelab-d0a18.appspot.com',
    measurementId: 'G-4G4634R9C0',
  );
}
